# Generated by Django 4.1 on 2022-10-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainmodel', models.CharField(max_length=25)),
                ('submodel', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('margin', models.IntegerField()),
            ],
        ),
    ]
