# Generated by Django 4.1 on 2022-10-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0002_regiscost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accmgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_code', models.CharField(max_length=20)),
                ('acc_name', models.CharField(max_length=100)),
                ('acc_price', models.IntegerField()),
                ('acc_type', models.CharField(max_length=10)),
                ('acc_model', models.CharField(max_length=10)),
            ],
        ),
    ]
