# Generated by Django 4.1 on 2022-10-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    

    dependencies = [
        ('sellmg', '0003_accmg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colorsubmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submodel', models.CharField( max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
