# Generated by Django 4.1 on 2022-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0004_accmg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tisconormal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fi_model', models.CharField(max_length=30)),
                ('fi_down', models.FloatField()),
                ('fi_in_48', models.FloatField()),
                ('fi_in_60', models.FloatField()),
                ('fi_in_72', models.FloatField()),
                ('fi_in_84', models.FloatField()),
            ],
        ),
    ]
