# Generated by Django 4.1.2 on 2022-11-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0010_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTRcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=30)),
                ('mainmodel', models.CharField(max_length=25)),
                ('customername', models.CharField(max_length=50)),
                ('contactcustomer', models.CharField(max_length=50)),
                ('chanelcustomer', models.CharField(max_length=10)),
                ('statuscustomer', models.CharField(max_length=10)),
            ],
        ),
    ]
