# Generated by Django 4.1.2 on 2022-11-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0011_htrcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='htrcustomer',
            name='remark',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='htrcustomer',
            name='statuscustomer',
            field=models.CharField(choices=[('PP', 'PP : ลูกค้ามุ่งหวัง'), ('BK', 'BK : ลูกค้าจอง'), ('DV', 'DV : ลูกค้าส่งมอบ'), ('TD', 'TD : ทดลองขับ'), ('F', 'F : ล้มเหลว')], default='PP', max_length=10),
        ),
    ]
