# Generated by Django 4.1.2 on 2022-11-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0012_htrcustomer_remark_alter_htrcustomer_statuscustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htrcustomer',
            name='statuscustomer',
            field=models.CharField(max_length=10),
        ),
    ]
