# Generated by Django 4.1.2 on 2022-11-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0013_alter_htrcustomer_statuscustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htrcustomer',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
