# Generated by Django 4.1.2 on 2022-11-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0014_alter_htrcustomer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htrcustomer',
            name='chanelcustomer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='htrcustomer',
            name='statuscustomer',
            field=models.CharField(max_length=30),
        ),
    ]
