# Generated by Django 4.1.4 on 2022-12-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0016_pathstatushtr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathstatushtr',
            name='id_htrcustomer',
            field=models.CharField(max_length=4),
        ),
    ]
