# Generated by Django 4.1.4 on 2022-12-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0017_alter_pathstatushtr_id_htrcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='htrcustomer',
            name='teamsell',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
