# Generated by Django 4.1.4 on 2022-12-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0018_htrcustomer_teamsell'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamsell', models.CharField(default='-', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=30)),
                ('mainmodel', models.CharField(max_length=25)),
                ('customername', models.CharField(max_length=50)),
                ('contactcustomer', models.CharField(max_length=50)),
                ('chanelcustomer', models.CharField(max_length=30)),
                ('statuscustomer', models.CharField(max_length=30)),
                ('remark', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pathstatusho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hocustomer', models.CharField(max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('statuscustomer', models.CharField(max_length=30)),
                ('remark', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pathstatusrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rscustomer', models.CharField(max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('statuscustomer', models.CharField(max_length=30)),
                ('remark', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RScustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamsell', models.CharField(default='-', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=30)),
                ('mainmodel', models.CharField(max_length=25)),
                ('customername', models.CharField(max_length=50)),
                ('contactcustomer', models.CharField(max_length=50)),
                ('chanelcustomer', models.CharField(max_length=30)),
                ('statuscustomer', models.CharField(max_length=30)),
                ('remark', models.CharField(default='-', max_length=100)),
            ],
        ),
    ]
