# Generated by Django 4.1.4 on 2022-12-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0019_hocustomer_pathstatusho_pathstatusrs_rscustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='HOcustomer',
        ),
        migrations.DeleteModel(
            name='Pathstatusho',
        ),
        migrations.DeleteModel(
            name='Pathstatusrs',
        ),
        migrations.DeleteModel(
            name='RScustomer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
