# Generated by Django 4.1.4 on 2022-12-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0020_remove_employee_user_delete_hocustomer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSAcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msabranch', models.CharField(default='-', max_length=20)),
                ('teamsell', models.CharField(default='-', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=30)),
                ('mainmodel', models.CharField(max_length=25)),
                ('customername', models.CharField(max_length=50)),
                ('contactcustomer', models.CharField(max_length=50)),
                ('chanelcustomer', models.CharField(max_length=30)),
                ('statuscustomer', models.CharField(max_length=30)),
                ('remark', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pathstatusmsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msabranch', models.CharField(default='-', max_length=20)),
                ('id_msacustomer', models.CharField(max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('statuscustomer', models.CharField(max_length=30)),
                ('remark', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='HTRcustomer',
        ),
        migrations.DeleteModel(
            name='Pathstatushtr',
        ),
    ]
