# Generated by Django 4.1.4 on 2022-12-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellmg', '0021_msacustomer_pathstatusmsa_delete_htrcustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msacustomer',
            name='quotation',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
